[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9"
pollster = "0.2"
anyhow = "1.0"
bytemuck = { version = "1.12", features = [ "derive" ] }

lyon = "1.0"

wgpu = "0.13"
winit = "0.27"
